
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: LEGACYHTML5
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/templates/
  datasource:
        url: jdbc:mysql://localhost:3306/volunteer?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
        username: root
        password: 123
        driver-class-name: com.mysql.jdbc.Driver

  redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000
      #pool:
      # 连接池中的最大空闲连接
      max-idle: 100
      min-idle: 0
      max-active: 200
      max-wait-millis: -1

# mybatis
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.volunteer.demo.DO
  config-location: classpath:Mybatis.xml
server:
  port: 8083

#logging
logging:
  # 日志文件路径
  path: /root/volunteer/



